In [19]:
import numpy as np
import scipy as sp
import xarray as xr

In [6]:
# compares each ordered list
np.less([0, 2], [2, 2]) 

# The < operator is shorthand for np.less
a = np.array([1, 2])
b = np.array([2, 2])
a < b

array([ True, False])

Similarly `np.greater` (and its corresponding `>` operator), `np.equal`, `np.not_equal` ,`np.greater_equal`, `np.less_equal`

In [7]:
np.greater([4,2],[2,2])

array([ True, False])

In [9]:
np.not_equal([1.,2.], [1., 3.])
np.not_equal([1, 2], [[1, 3],[1, 4]])

array([[False,  True],
       [False,  True]])

use `np.newaxis` to create an additional dimension. Note that `...` mean "all existing dimensions"

In [17]:
w = sp.stats.beta.rvs(1, 2, size=(5, 7))
w_new = w[...,np.newaxis]
print(w.shape); print(w_new.shape)
w_new[:,:,0]

(5, 7)
(5, 7, 1)


array([[0.64299986, 0.54903494, 0.10562734, 0.07865629, 0.28732737,
        0.03300348, 0.5899945 ],
       [0.12736561, 0.89450152, 0.12037716, 0.13882787, 0.0894069 ,
        0.76801874, 0.50005129],
       [0.24431904, 0.22420228, 0.17068029, 0.15105974, 0.40203086,
        0.34891973, 0.03755223],
       [0.17622042, 0.32469711, 0.57692601, 0.71701272, 0.31364174,
        0.29644377, 0.5948393 ],
       [0.73411327, 0.27811129, 0.29175509, 0.48892214, 0.11371944,
        0.14033999, 0.33629881]])

`xrray` module contains a data structure called `DataArray`

https://docs.xarray.dev/en/stable/getting-started-guide/quick-overview.html

In [21]:
# dims and coords are optional arguments that one can pass
# we have generated a 2D array, assigned the names x and y to the two dimensions and associated two coordinate labels ‘10’ and ‘20’ with the two locations along the x dimension.
data = xr.DataArray(np.random.randn(2, 3), dims=("x", "y"), coords={"x": [10, 20]})
data

<xarray.DataArray (x: 2, y: 3)>
array([[ 0.73744784, -1.37909558, -0.09490765],
       [-1.56419224, -0.99272394, -1.01573077]])
Coordinates:
  * x        (x) int32 10 20
Dimensions without coordinates: y

In [25]:
np.less_equal(range(1,8),range(1,8))

array([ True,  True,  True,  True,  True,  True,  True])

In [23]:
# outer performs all pairwise comparisons
np.less_equal.outer(range(1,8),range(1,8))

array([[ True,  True,  True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True,  True,  True],
       [False, False,  True,  True,  True,  True,  True],
       [False, False, False,  True,  True,  True,  True],
       [False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True],
       [False, False, False, False, False, False,  True]])